name: Deploy website

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy to production
        run: |
          ssh -p 2222 \
            -o StrictHostKeyChecking=no \
            deploy@169.58.39.42 \
            'cd /home/deploy/marko-jovanovic-portfolio && git pull --ff-only origin main && cp -r web/. /var/www/marko.jovanovic.pro/'
