name: Runner Test

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Test SSH connection
        run: |
          ssh -p 2222 \
            -o StrictHostKeyChecking=no \
            deploy@169.58.39.42 \
            'whoami && hostname'
